### ISSUE TITLE
multiple: true support for args

### ISSUE THREAD

**Issue by ivan** [funbox/optimus#3]
I think it would be nice to have `multiple: true` support for args.  I suppose it would only work for the last argument in an args list.

I just noticed this is possible to DIY with `allow_unknown_args: true`, but that results in slightly misleading help information.

**Comment by savonarola** [comment]
Hello!

Thanks for the feedback. Could you please give little more details about the misleading generated help?

**Comment by ivan** [comment]
Sure.  I just mean that while you can process the unknown args yourself, optimus can only show help as if it takes a single argument:

```
# mm help tag
Machine Manager
Add tags to a machine

USAGE:
    machine_manager tag HOSTNAME TAG

ARGS:

    HOSTNAME                                                                    
    TAG             Tag to add                              
```

clap-rs would show `<TAG>...` for 1-or-more arguments and `[TAG]...` for 0-or-more arguments.

**Comment by ivan** [comment]
`value_name: "TAG..."` sort of works as a half-baked workaround, but when using `required: false` you get `[TAG...]` instead of `[TAG]...` in the help.

Anyway, I am happy I can do this with the unknown args parsing, at least, so thank you for putting that in.

**Comment by savonarola** [comment]
Hello!

Tried to fix the issue, the new behavior is specified in this test: https://github.com/savonarola/optimus/blob/master/test/optimus/usage_test.exs#L83
