### ISSUE TITLE
Could not get defaults to work

### ISSUE THREAD

**Issue by dwhelan** [funbox/optimus#9]
I was setting up a default option but after parsing it remained `nil`. I was expecting it to return the value as the default. Then I realized that the version with the `default` support has not been pushed to [hex.pm](https://hex.pm/packages/optimus). I would love to use that feature!

When are you planning the next release?

**Comment by savonarola** [comment]
Hello!

Thanks for the feedback. I'll try to push a  new release shortly.

**Comment by savonarola** [comment]
Here it is: https://hex.pm/packages/optimus/0.1.6
